// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9PzxRb9A4-DXaZ3YotBlZmg8puCRrEw',
    appId: '1:55319028100:android:e8b3739ac1eaaa9301bdd1',
    messagingSenderId: '55319028100',
    projectId: 'todo-app-firebase-flutte-a1278',
    storageBucket: 'todo-app-firebase-flutte-a1278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpCiKIY_jsFdb1dbFbneimWGdBKAX6iI',
    appId: '1:55319028100:ios:eec0688b0939606101bdd1',
    messagingSenderId: '55319028100',
    projectId: 'todo-app-firebase-flutte-a1278',
    storageBucket: 'todo-app-firebase-flutte-a1278.firebasestorage.app',
    iosClientId: '55319028100-fu586q4i2jfm879vgmkhq7n4u1bk5ic6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppFirebaseFlutter',
  );
}
